### PR TITLE
place all tests files one level higher, reference ans explicitly

### PR DESCRIPTION
**Pull request by eddelbuettel**
We (historically) had the test file files in a directory `tests/` which is what the test runner expects, and because I was extra-paranoid at the very beginning, had _that_ directory in a directory `tests/`.   Department of redundant redundancy.  

I had been thinking I would need to generalized the `plr` package to cope with either but not so---this is actually driven by `pltest.R` _inside each question repository in a single place_.  So I figured it would be a good time to rip the band aid and just made the change over morning coffee.  

Comments welcome.  I picked two volunteers^Hcrazies who already joined to review.   Runs as above as I also updated the relative path for the reference answer to an absolute one which is better either way.   A clean start for new questions!

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@barbehenna is more awake today that I was last evening and alerted me to the fact (and long committed) that `run.sh` needed changes too.

**Comment by barbehenna** [comment]
A potentially important implication of this PR is that the ag user will be given ownership of `ans.R`. We can take steps to avoid or correct this, but they may end up costing us in the complexity or generality of the autograder. 

One option is to specifically target the test functions using a pattern in the file names and change their ownership (possibly making them a subdirectory again). Another option is to specifically make root the owner of the `ans.R` again. Either of these approaches can be done in `run.sh` or `pltest.R`. I'm sure there are many other solutions we could consider if this is an issue we wish to handle.

**Comment by eddelbuettel** [comment]
>  the ag user will be given ownership of ans.R.

Forgot to mention that when we riffed over Slack.   We could avoid this by changing line 39 to the equivalent of `chown ag:ag test*R`, maybe by adding a new MERGE_FILES="${JOB_DIR}test_*"     (or, if the slash gets moved of JOB_DIR,   `${JOB_DIR}/test*[rR]`).  

The net-net is that what we currently have works flawlessly but it ugly with the `tests/tests/test_*[rR]` files.  I think we can remove some of the uglyness without running into obstacles (that our younger selfes were worried about two years ago in the initial version).

(And you're aware per

> One option is to specifically target the test functions using a pattern in the file names 

noted in your comment)

**Comment by eddelbuettel** [comment]
So ... this stalled and we never really got to a review stage which is a pity.  I would have appreciate input from either @firasm or @daviddalpiaz or, ideally, both.

I want to make some other changes, and as nested PRs are a little crazy, and not need at this stage I am going to merge this one now and proceed with another small cleanup to run.sh and friends that has been bugging me.

**Comment by firasm** [comment]
My apologies @eddelbuettel !! This got buried. 

My classes this term have just switched to online and ... AHHHH!

I'm rapidly running out of capacity to to try new cool, things like this before term starts.

I think soldier on - I trust implicitly all decisions you make (though I understand the importance of code review)! When I have some time to contribute I surely will. I've starred the repo

**Comment by eddelbuettel** [comment]
There is another (new) PR here and I think I will (barring alternatives ...) "soldier on" as this is after all a demo repo.  @barbehenna  and I will evaluate if we bet the new course on this layout. I think we can but I will await his input on that over there.

Overall I like where this is going so come back as you find pockets of time (I hear you going "hah, as if ..." :smiley:

**Pull request merged**
